export default {
  credit: "Davis Instruments Corp.",
  credit_URL: "http://www.davisnet.com",
  disclaimer_url: "http://www.davisnet.com/about/terms.asp",
  copyright_url: "http://www.davisnet.com/about/terms.asp",
  privacy_policy_url: "http://www.davisnet.com/about/privacy.asp",
  image: {
    url: "http://www.weatherlink.com/images/Logo_Davis_reflxblu.jpg",
    title: "Davis WeatherLink",
    link: "http://www.weatherlink.com",
  },
  suggested_pickup: "15 minutes after the hour",
  suggested_pickup_period: "60",
  dewpoint_c: "0.6",
  dewpoint_f: "33.0",
  dewpoint_string: "33.0 F (0.6 C)",
  heat_index_c: "10.6",
  heat_index_f: "51.0",
  heat_index_string: "51.0 F (10.6 C)",
  location: "USA",
  latitude: "45.8",
  longitude: "6.9",
  observation_time: "Last Updated on Mar 15 2021, 5:27 pm CET",
  observation_time_rfc822: "Mon, 15 Mar 2021 17:27:44 +0100",
  pressure_in: "29.758",
  pressure_mb: "1007.7",
  pressure_string: "1007.7 mb",
  relative_humidity: "51",
  station_id: "demo",
  temp_c: "10.5",
  temp_f: "50.9",
  temperature_string: "50.9 F (10.5 C)",
  wind_degrees: "173",
  wind_dir: "South",
  wind_kt: "0.0",
  wind_mph: "0.0",
  windchill_c: "10.6",
  windchill_f: "51.0",
  windchill_string: "51.0 F (10.6 C)",
  davis_current_observation: {
    DID: "001D0A00DE6A",
    station_name: "API",
    observation_age: 7054714,
    dewpoint_day_high_f: "35",
    dewpoint_day_high_time: "10:33am",
    dewpoint_day_low_f: "23",
    dewpoint_day_low_time: "4:50am",
    dewpoint_month_high_f: "41",
    dewpoint_month_low_f: "23",
    dewpoint_year_high_f: "41",
    dewpoint_year_low_f: "23",
    et_day: "0.068",
    et_month: "0.040",
    et_year: "0.040",
    heat_index_day_high_f: "54",
    heat_index_day_high_time: "1:40pm",
    heat_index_month_high_f: "54",
    heat_index_year_high_f: "54",
    pressure_day_high_in: "29.901",
    pressure_day_high_time: "9:12am",
    pressure_day_low_in: "29.743",
    pressure_day_low_time: "3:26pm",
    pressure_month_high_in: "29.901",
    pressure_month_low_in: "29.650",
    pressure_tendency_string: "Steady",
    pressure_year_high_in: "29.901",
    pressure_year_low_in: "29.650",
    rain_day_in: "0.0000",
    rain_month_in: "0.0945",
    rain_rate_day_high_in_per_hr: "0.0000",
    rain_rate_hour_high_in_per_hr: "0.0000",
    rain_rate_in_per_hr: "0.0000",
    rain_rate_month_high_in_per_hr: "0.7795",
    rain_rate_year_high_in_per_hr: "0.7795",
    rain_storm_in: "0.0000",
    rain_year_in: "0.0945",
    relative_humidity_day_high: "94",
    relative_humidity_day_high_time: "6:05am",
    relative_humidity_day_low: "35",
    relative_humidity_day_low_time: "1:38pm",
    relative_humidity_month_high: "94",
    relative_humidity_month_low: "35",
    relative_humidity_year_high: "94",
    relative_humidity_year_low: "35",
    relative_humidity_in: "38",
    relative_humidity_in_day_high: "40",
    relative_humidity_in_day_high_time: "12:01am",
    relative_humidity_in_day_low: "37",
    relative_humidity_in_day_low_time: "11:08am",
    relative_humidity_in_month_high: "56",
    relative_humidity_in_month_low: "37",
    relative_humidity_in_year_high: "56",
    relative_humidity_in_year_low: "37",
    solar_radiation: "37",
    solar_radiation_day_high: "735",
    solar_radiation_day_high_time: "12:54pm",
    solar_radiation_month_high: "735",
    solar_radiation_year_high: "735",
    sunrise: "6:24am",
    sunset: "6:17pm",
    temp_day_high_f: "56.3",
    temp_day_high_time: "1:55pm",
    temp_day_low_f: "25.0",
    temp_day_low_time: "6:21am",
    temp_month_high_f: "56.3",
    temp_month_low_f: "25.0",
    temp_year_high_f: "56.3",
    temp_year_low_f: "25.0",
    temp_in_day_high_f: "69.3",
    temp_in_day_high_time: "12:09am",
    temp_in_day_low_f: "65.7",
    temp_in_day_low_time: "9:00am",
    temp_in_f: "68.7",
    temp_in_month_high_f: "73.7",
    temp_in_month_low_f: "62.5",
    temp_in_year_high_f: "73.7",
    temp_in_year_low_f: "62.5",
    uv_index: "0.0",
    uv_index_day_high: "3.2",
    uv_index_day_high_time: "11:59am",
    uv_index_month_high: "3.2",
    uv_index_year_high: "3.2",
    wind_day_high_mph: "14.0",
    wind_day_high_time: "2:26pm",
    wind_month_high_mph: "17.0",
    wind_ten_min_avg_mph: "1.0",
    wind_ten_min_gust_mph: "5.0",
    wind_year_high_mph: "17.0",
    windchill_day_low_f: "24",
    windchill_day_low_time: "5:21am",
    windchill_month_low_f: "24",
    windchill_year_low_f: "24",
  },
  time_to_generate: "0.008409 seconds",
};
