export const TEN_SECONDS_IN_MILLISECONDS = 10000;
export const CELSIUS = "℃";
export const DEGREES = "°";
export const MILLIBAR_MB = "millibar (mb)";
export const PERCENT = "%";
export const METERS_PER_SECOND_MS = "meters per second (m/s)";
export const INCHES = "in";
export const MILLIMETERS = "mm";
export const MILES_PER_HOUR = "mph";